config/routes.rb
Myflix::Application.routes.draw do
  root to: 'pages#front'
  get 'home', to: "videos#index"
  get 'ui(/:action)', controller: 'ui'

  resources :videos, only: [:show, :index] do
    collection do
      get :search, to: "videos#search"
    end
    resources :reviews, only: [:create]
  end

  namespace :admin do
    resources :videos, only: [:new, :create]
  end

  resources :queue_items, only: [:create, :destroy]
  get 'my_queue', to: 'queue_items#index'
  post 'update_queue', to: 'queue_items#update_queue'

  get 'register', to: 'users#new'
  get 'register/:token', to: 'users#new_with_invitation_token', as: 'register_with_token'
  get 'sign_in', to: 'sessions#new'
  get 'sign_out', to: 'sessions#destroy'

  resources :users, only: [:create, :show]
  resources :sessions, only: [:create]

  resources :categories, except: [:destroy]
  get 'people', to: 'relationships#index'
  resources :relationships, only: [:index, :create, :destroy]

  get 'forgot_password', to: 'forgot_passwords#new'
  get 'forgot_password_confirmation', to: 'forgot_passwords#confirm'
  resources :forgot_passwords, only: [:create]
  resources :password_resets, only: [:show, :create]
  get 'expired_token', to: 'pages#expired_token'

  resources :invitations, only: [:new, :create]
end

app/models/video.rb
class Video < ActiveRecord::Base
  has_many :video_categories
  has_many :categories, through: :video_categories
  has_many :reviews, -> { order 'created_at DESC' }
  has_many :queue_items
  accepts_nested_attributes_for  :categories

  mount_uploader :large_cover_image, LargeCoverUploader
  mount_uploader :small_cover_image, SmallCoverUploader

  validates_presence_of :title, :description

  def self.search_by_title(search_term)
    return [] if search_term.blank?
    where("title LIKE ?", "%#{search_term}%").order("created_at DESC")
  end

  def rating
    return 0.0 if self.reviews.count == 0
    sum = self.reviews.reduce(0.0) { |sum, review| sum + review.rating  }
    "%.1f" % ( sum / self.reviews.count )
  end
end

app/controllers/admin/videos_controller.rb
class Admin::VideosController < ApplicationController
  before_filter :require_user
  before_filter :require_admin

  def new
    @video = Video.new
  end

  def create
    @video = Video.new(video_params)
    if @video.save
      flash[:success] = "You have successfully added the video #{@video.title}."
      redirect_to new_admin_video_path
    else
      flash[:error] = "Video wasn't added. Please check the error/s."
      render :new
    end
  end

private
  def require_admin
    if !current_user.admin?
      flash[:error] = 'You are not authorized to that.'
      redirect_to home_path
    end
  end

  def video_params
    params.require(:video).permit!
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_filter :require_user

  def index
    @categories = Category.all
  end

  def show
    @video = VideoDecorator.decorate(Video.find(params[:id]))
    @reviews = @video.reviews
  end

  def search
    @results = Video.search_by_title(params[:search_term])
  end
end

app/helpers/video_helper.rb
module VideoHelper
end

app/views/videos/index.html.haml
- @categories.each do |category|
  - unless category.videos.empty?
    %article.video_category
      %header
        %h3= link_to category.name, category_path(category)
      .videos.row
        - category.recent_videos.each do |video| 
          .video.col-sm-2
            = link_to video_path(video) do
              %img(src="#{video.small_cover_image}")

app/views/videos/search.html.haml
%article.video_category
  - @results.each do |video| 
    .video.col-sm-2
      = link_to video_path(video) do
        %img(src="#{video.small_cover_image}")

app/views/videos/show.html.haml
%article.video
  .container
    .row
      .video_large_cover.col-sm-7.col-sm-offset-1
        %img(src="#{@video.large_cover_image}")
      .video_info.col-sm-3
        %header
          %h3= @video.title
          %span Rating:
          = @video.rating
        %p= @video.description
        .actions
          %a.btn.btn-primary(href="#{@video.video_url}") Watch Now
          = link_to "+ My Queue", queue_items_path(video_id: @video.id), method: :post, class: 'btn' unless current_user.queued_video?(@video)

%section.reviews.container
  .row
    .span10.offset1
      = form_for [@video, Review.new] do |f|
        %fieldset
          %label Rate this video
          = f.select :rating, options_for_video_reviews(), include_blank: true
          %br
          %br
          %label Write Review
          = f.text_area :description, rows: 6, cols: 100, class: "span6"
          %fieldset.actions.clearfix
            %input(type="submit" value="Submit" class="btn")
            = link_to "Cancel", @video
      %header
        %h3= "User Reviews (#{@reviews.count})"
      %ul
        - @reviews.each do |review|
          %article.review
            %li.row
              .span2
                %span Rating: #{review.rating} / 5
                %p by 
                = link_to review.user.full_name, review.user
              .span8
                %p= review.description