config/routes.rb
Myflix::Application.routes.draw do
  root to: 'pages#front'
  get 'home', to: "videos#index"
  get 'ui(/:action)', controller: 'ui'

  resources :videos, only: [:show, :index] do
    collection do
      get :search, to: "videos#search"
    end
    resources :reviews, only: [:create]
  end

  namespace :admin do
    resources :videos, only: [:new, :create]
  end

  resources :queue_items, only: [:create, :destroy]
  get 'my_queue', to: 'queue_items#index'
  post 'update_queue', to: 'queue_items#update_queue'

  get 'register', to: 'users#new'
  get 'register/:token', to: 'users#new_with_invitation_token', as: 'register_with_token'
  get 'sign_in', to: 'sessions#new'
  get 'sign_out', to: 'sessions#destroy'

  resources :users, only: [:create, :show]
  resources :sessions, only: [:create]

  resources :categories, except: [:destroy]
  get 'people', to: 'relationships#index'
  resources :relationships, only: [:index, :create, :destroy]

  get 'forgot_password', to: 'forgot_passwords#new'
  get 'forgot_password_confirmation', to: 'forgot_passwords#confirm'
  resources :forgot_passwords, only: [:create]
  resources :password_resets, only: [:show, :create]
  get 'expired_token', to: 'pages#expired_token'

  resources :invitations, only: [:new, :create]
end

app/views/shared/_header.html.haml
%section#top-header.row
  %h1.col-md-2
    = link_to "MyFLiX"
  %ul.col-md-4.clearfix
    %li= link_to("Videos", videos_path)
    %li= link_to("My Queue", my_queue_path)
    %li= link_to("People", people_path)
  = form_tag search_videos_path, method: :get, class: "span5 for-search" do
    %input.form-control(name="search_term" type="text" placeholder="Search for videos here")
    %button.btn.btn-default(type="submit") Search
  #user_links.pull-right
    %ul
      %li.dropdown
        %a(href="#" id="dlabel" role="button" data-toggle="dropdown" class="dropdown-toggle" data-target="#")
          - if current_user
            Welcome, #{current_user.full_name}
            %b.caret
        %ul.dropdown-menu(role="menu" aria-labelledby="dlabel")
          %li
            = link_to("Invite a friend", new_invitation_path)
            %a(href="#") Account
            %a(href="#") Plan and Billing
            = link_to("Sign Out", sign_out_path)

app/views/shared/_messages.html.haml
- flash.each do |name, msg|
  %div(class="alert #{twitterized_type(name)}")
    %a.close(data-dismiss='alert') &#215;
    = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)