config/routes.rb
Myflix::Application.routes.draw do
  root to: 'pages#front'
  get 'home', to: "videos#index"
  get 'ui(/:action)', controller: 'ui'

  resources :videos, only: [:show, :index] do
    collection do
      get :search, to: "videos#search"
    end
    resources :reviews, only: [:create]
  end

  namespace :admin do
    resources :videos, only: [:new, :create]
  end

  resources :queue_items, only: [:create, :destroy]
  get 'my_queue', to: 'queue_items#index'
  post 'update_queue', to: 'queue_items#update_queue'

  get 'register', to: 'users#new'
  get 'register/:token', to: 'users#new_with_invitation_token', as: 'register_with_token'
  get 'sign_in', to: 'sessions#new'
  get 'sign_out', to: 'sessions#destroy'

  resources :users, only: [:create, :show]
  resources :sessions, only: [:create]

  resources :categories, except: [:destroy]
  get 'people', to: 'relationships#index'
  resources :relationships, only: [:index, :create, :destroy]

  get 'forgot_password', to: 'forgot_passwords#new'
  get 'forgot_password_confirmation', to: 'forgot_passwords#confirm'
  resources :forgot_passwords, only: [:create]
  resources :password_resets, only: [:show, :create]
  get 'expired_token', to: 'pages#expired_token'

  resources :invitations, only: [:new, :create]
end

app/models/video.rb
class Video < ActiveRecord::Base
  has_many :video_categories
  has_many :categories, through: :video_categories
  has_many :reviews, -> { order 'created_at DESC' }
  has_many :queue_items
  accepts_nested_attributes_for  :categories

  mount_uploader :large_cover_image, LargeCoverUploader
  mount_uploader :small_cover_image, SmallCoverUploader

  validates_presence_of :title, :description

  def self.search_by_title(search_term)
    return [] if search_term.blank?
    where("title LIKE ?", "%#{search_term}%").order("created_at DESC")
  end

  def rating
    return 0.0 if self.reviews.count == 0
    sum = self.reviews.reduce(0.0) { |sum, review| sum + review.rating  }
    "%.1f" % ( sum / self.reviews.count )
  end
end

app/controllers/admin/videos_controller.rb
class Admin::VideosController < ApplicationController
  before_filter :require_user
  before_filter :require_admin

  def new
    @video = Video.new
  end

  def create
    @video = Video.new(video_params)
    if @video.save
      flash[:success] = "You have successfully added the video #{@video.title}."
      redirect_to new_admin_video_path
    else
      flash[:error] = "Video wasn't added. Please check the error/s."
      render :new
    end
  end

private
  def require_admin
    if !current_user.admin?
      flash[:error] = 'You are not authorized to that.'
      redirect_to home_path
    end
  end

  def video_params
    params.require(:video).permit!
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_filter :require_user

  def index
    @categories = Category.all
  end

  def show
    @video = VideoDecorator.decorate(Video.find(params[:id]))
    @reviews = @video.reviews
  end

  def search
    @results = Video.search_by_title(params[:search_term])
  end
end

app/helpers/video_helper.rb
module VideoHelper
end

app/views/admin/videos/new.html.haml
%section.admin_add_video.container
  .row
    .col-sm-10.col-sm-offset-1
      = bootstrap_form_for [:admin, @video], html: { class: 'form-horizontal' } do |f|
        %ul.nav.nav-tabs
          %li
            %a(href="") Recent Payments
          %li.active
            %a(href="") Add a New Video
        %fieldset
          = f.text_field :title, label: "Title"
          = f.select :category_ids, options_for_select(Category.all.map {|c| [c.name, c.id]}), label: "Category"
          = f.text_area :description, rows: 8, label: "Description"
          = f.file_field :large_cover_image, class: "btn btn-file"
          = f.file_field :small_cover_image, class: "btn btn-file"
          = f.text_field :video_url, class: "span3", label: 'Video URL'
        %br
        %fieldset.form-group.action
          .controls
            %input(type="submit" value="Add Video" class="btn btn-default")